CREATE TABLE IF NOT EXISTS `user_permission` (
  `id` VARCHAR(45) NOT NULL,
  `name` ENUM('ADD_SHOW','EDIT_SHOW','ADD_USER','EDIT_USER','ADD_VENUE','EDIT_VENUE','ADD_REVIEW','EDIT_REVIEW','ADD_RATING','EDIT_RATING','ADD_EVENT','EDIT_EVENT','ADD_PRODUCTION_COMPANY','EDIT_PRODUCTION_COMPANY') NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `entity_id` VARCHAR(45),
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME,
  `created_by` VARCHAR(45) NOT NULL,
  `updated_by` VARCHAR(45),
  `is_deleted` varchar(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;